### ISSUE TITLE
Tool installs but does not start

### ISSUE THREAD

**Issue by WavEC** [DTOcean/dtocean#13]
I maanage to install the software, but when i try to run the tool, the "DTOcean" logo pop's up, but after a while disappears and nothing else happens, I noticed that the process "pythonw" which started when i run the tool, also shuts down, when the logo disappears.

**Comment by H0R5E** [comment]
OK, to diagnose what it going on begin with right clicking on the DTOcean GUI shortcut and selecting "Properties".

Open a command prompt (cmd.exe) and change the directory to the one given in the "Start in:" box and then run the command shown in the "Target:" box in the properties dialogue. The process should look a little like this:

```
>> cd C:\DTOcean\Scripts
>> C:\DTOcean\python.exe C:\DTOcean\Scripts\dtocean-gui-script.py
```

Note, I changed the interpretor to python.exe above just in case pythonw disguises the error. You should get a stack trace which will reveal what is happening which you can post here.

**Comment by WavEC** [comment]
This was the traceback i got:
![image](https://cloud.githubusercontent.com/assets/25801019/23026479/4a60c6d0-f459-11e6-87c7-39e6ef4d8332.png)
its seems some dll is not found...

**Comment by H0R5E** [comment]
Do you have QtWebKit.pyd in the directory C:\DTOcean\Lib\site-packages\PyQt4? I have it with size 414KB.

If not something has gone wrong with your installation.

**Comment by WavEC** [comment]
I have the file, the exact some size, 414kB.

**Comment by H0R5E** [comment]
Can you try the procedure described in the following post?

http://stackoverflow.com/questions/22221427/importerror-dll-load-failed-the-specified-procedure-could-not-be-found-python

It might reveal what is missing on your system.

**Comment by H0R5E** [comment]
I'm struggling to recreate your problem. It looks like the pyd files are looking for some missing DLLs or reading the wrong DLLs.

What is on your path environment variable?

In a command window type "echo $PATH$" and it will be printed.

**Comment by WavEC** [comment]
So, i had a look at the link you sent, but could not be sure what steps you meant to take.

I installed Qt4.8.4 and placed the dll files in C:\Qt\4.8.4\bin in the dtocean folder (in the link: The solution is to put Qt libraries version 4.8.4 into your '%PYTHONHOME%\Lib\site-packages\PyQt4' folder or PATH.).

 I also added "C:\Qt\4.8.4\bin" to the Environment Variables in advanced settings of windows system.
When i run the command you sent i just get "$PATH$".

However, in the settings the listing is as follows:
![image](https://cloud.githubusercontent.com/assets/25801019/23031143/db70a998-f467-11e6-9459-f831362ed7b8.png)

**Comment by WavEC** [comment]
And the "Dependency Walker" shows a lot of red dependencies when opening the QtWebKit.pyd...

**Comment by H0R5E** [comment]
Sorry should have been "echo %PATH%".

My best guess is that you have some 32bit DLLs which are being linked incorrectly. There should be a file in C:\DTOcean called qt.conf and this should direct Qt to look in C:/DTOcean/Library/bin for the DLLs. However, I think it will look in other places first, so it might be that its loading the wrong DLLs.

The way I found out which DLLs were being loaded on my system was by using Process Monitor:

https://technet.microsoft.com/en-us/sysinternals/bb896645.aspx

Its pretty complicated but if you go to Tools->Process Tree you can then find the process of your command window to see which DDLs it is trying to load. Rather than starting DTOcean, you might just start python (exclude the link to the script) and in the interpretor type:

from PyQt4.QtWebKit import QWebView

Now if you right click the process in Process Monitor and click "Go To Event" it should take you to the start of the python session. Scroll down and look for DLL files - it should tell you where it looked and whether it successfully found them. My idea is that it is finding the wrong ones on your system.

**Comment by H0R5E** [comment]
If you click "Include Subtree" on the process tree viewer, once you have selected the python session, it will also filter out the other processes.

**Comment by H0R5E** [comment]
I'm going to close this due to inactivity.
