### ISSUE TITLE
DTOcean 1.x tutorial 1 "supporting data" incompatible with DTOcean 2.x

### ISSUE THREAD

**Issue by NajiyaN** [DTOcean/dtocean#28]
I am trying to read in the fixed tidal tutorial file /any input file and I am getting an import error.
eg -An ImportError occurred:no module named moorings.

Appreciate any pointers to solve this.

**Comment by H0R5E** [comment]
Hello @NajiyaN,

It sounds to me like you have some sort of backwards compatibility problem. You will need to provide more information if I am to help you, however. Can you tell me:

1. Which version of DTOcean are you using? (Open the GUI and then open the "About DTOcean..." dialogue from the "Help" menu. The version number is below the banner.)

2. How did you install it? (Using an installation wizard, anaconda, or from source?)

3. Which files are you using and where did you get them?

4. What process are you using to read the files?

5. Precisely what error are you getting? (You can copy and paste the full error from the System dock)

Cheers,

Mat

**Comment by NajiyaN** [comment]
Hi Mat,

Thank you for getting back on this. Please find below details as requested.

I have also attached the snapshot of the error. Please let me know if you
need more information.

Thanks
Najiya

**Comment by H0R5E** [comment]
Najiya, I don't think the attachment worked, but, in general the files on the SETIS website will not work in DTOcean 2.0. 

What are you trying to do? If you just want a tidal example to play with, I can send you an alternative file.

Alternatively you can create a tidal example using the database following this guide:

https://dtocean.github.io/user/getting_started_2.html

**Comment by NajiyaN** [comment]
Mat, Incompatibility between the file and version of software could be the case. I can't attach the error pic. The error "An ImportError occurred - No module named mooring".

I am working on tidal turbine foundations so , a tidal example would be helpful. I tried the database method but its throwing an error when i try to run the foundation module - "A RuntimeError occrred- No suitable grid points found for placing foundation". I got the same error with two different databases. Would you be able to point me why this may be? 

Thanks
Najiya

**Comment by H0R5E** [comment]
OK, I'll prepare a file for you (in .dts format) that you can import data from. Note, however, that you can't edit the data in a .dts file. Also, it will take me a couple of days to get it ready.

Regarding the foundation module error, this is probably due to the devices being placed too close to the edge of your domain. If you are using the hydrodynamics module to set the layout, then try increasing the size of the "Lease Area Boundary Padding" variable. If you are using a fixed layout, then manually move the positions of the devices away from the lease area boundary.

This new question is a bit off-topic for this issue, so if you would like to continue, can you pose a question on https://engineering.stackexchange.com/ ? This is a more appropriate place for modelling based discussions. If you do ask a question there, then post a link here and I will try and help.

**Comment by H0R5E** [comment]
OK. so I've attached the promised ".dts" file in a zip folder. Instead of using the "Load test data..." context-menu action, go to the "Data" menu in the menubar and select "Import (skip satisfied)...". Then select the "tidal_12MW_example.dts" file (after you have unzipped it). I've attached an image to help you find the import action.

![import_data](https://user-images.githubusercontent.com/5088535/59670392-c6ae5c80-91b3-11e9-9888-dbc73abbf4af.png)

[tidal_12MW_example.zip](https://github.com/DTOcean/dtocean/files/3300788/tidal_12MW_example.zip)
