### ISSUE TITLE
v1.0 Installer Failing

### ISSUE THREAD

**Issue by davidbould** [DTOcean/dtocean#3]
Although the installer (combined installer - DTOcean code plus Hydro data) works on the majority of systems, a number of users are reporting that it terminates abnormally.

The installation of the DTOcean code progresses well and seems to complete but the Hydro data installer then complains that "DTOcean installation directory not found."

Have double checked that c:\dtocean is the installation directory and that correct options during installation (e.g. regarding Python PATH variables) are being chosen. Have attempted running installer as Administrator.

Standalone Hydro Data installer works but main DTOcean code can still not be started (shortcuts in Start menu have not been created and opening dtocean-gui script from installation directory bombs out without error messages).

Unsure of OS for all users reporting this problem but at least some are running Windows 10.

**Comment by H0R5E** [comment]
So, in order to capture the installation directory chosen by the user in the Constructor installer, a post-install script is executed which should write this directory to the HKCU\Software\DTOcean key.

For some reason this is not working on all systems. There are three possibilities as far as I see it:

1. The script is failing. This could be from the commands not being recognised on certain systems (or within certain shells).
2. The user does not have sufficient rights to either run the script or write to the registry
3. Anti-virus software is blocking the execution of the script.

I think the easiest workaround for this is to modify this post install script so it excepts a directory location from the user. The user should then reinstall DTOcean using the address supplied to the script (ensuring the directory does not exist before starting).

This workaround has been tested manually for a user suffering this issue and it fixed the problem. I will publish the script and some instructions in the near future.

**Comment by H0R5E** [comment]
OK, the following gist is a batch script that will allow the user to pre-set the installation directory before installing DTOcean:

https://gist.github.com/H0R5E/1b2f915f9f4e44ed179614e4b54e4d41

Note that the chosen installation directory should be exactly replicated when prompted in the installer and must not exist prior to installation (it doesn't have to exist for the script to work).

Remember to uninstall or delete any existing DTOcean installation directories before reinstalling.

The user can verify the success of the script by running regedit.exe and looking for the key HKEY_CURRENT_USER\Software\DTOcean. The INSTALL_DIR subkey should contain the value set by the pre-install script.

**Comment by H0R5E** [comment]
Fixes applied in version 2.0.0 installer
