### ISSUE TITLE
The input velocity field is highly rotational - Error

### ISSUE THREAD

**Issue by anupjn** [DTOcean/dtocean#32]
Hi,

Been trying to use the hydrodynamic module within DTO2 with some fixed tidal device input data sets. With the same input tidal data, the hydrodynamic module worked in DTO1. That said, every time I run the hydrodynamic module in DTO2, it throws up this error (please see the "System" window text copied below):

CRITICAL - dtocean_app.main - An IOError occurred: [Errno The input velocity field is highly rotational ] This violate the model assumption : 'The execution is terminated'

This is something to do with the irrotational flow check in the code, but I am not sure why this error is raised only in DTO2. I must add that I tried running 4 different tidal velocity datasets (which all worked in DTO1) to see if any of them would work in DTO2. Unfortunately, they did not and gave the same error every time.

We did a diff between the relevant part of the code in DTO1 and DTO2 and found a few minor changes, but we could not identify any reason for DTO2 to act differently from DTO1. 

Any help on this matter would be greatly appreciated. Thank you. 

********************************************************
These are the messages in the "System" window in the GUI - 

2019-07-05 20:30:18,500 - INFO - dtocean_core.menu - Executing module 'Hydrodynamics'
2019-07-05 20:30:19,885 - CRITICAL - dtocean_app.main - An IOError occurred: [Errno The input velocity field is highly rotational ] This violate the model assumption : 'The execution is terminated'
2019-07-05 20:30:19,903 - CRITICAL - dtocean_app.main -   File "C:\Users\anambiar\DTOCEAN\lib\site-packages\dtocean_app\main.py", line 433, in run
    self._project)
  File "C:\Users\anambiar\DTOCEAN\lib\site-packages\dtocean_core\menu.py", line 471, in execute_current
    allow_unavailable=allow_unavailable)
  File "C:\Users\anambiar\DTOCEAN\lib\site-packages\dtocean_core\menu.py", line 168, in _execute
    set_output_level=set_output_level)
  File "C:\Users\anambiar\DTOCEAN\lib\site-packages\dtocean_core\core.py", line 2026, in execute_interface
    interface = core.connect_interface(project, interface)
  File "C:\Users\anambiar\DTOCEAN\lib\site-packages\dtocean_app\core.py", line 297, in connect_interface
    interface = super(GUICore, self).connect_interface(project, interface)
  File "C:\Users\anambiar\DTOCEAN\lib\site-packages\dtocean_core\core.py", line 1508, in connect_interface
    interface.connect()
  File "C:\Users\anambiar\DTOCEAN\lib\site-packages\dtocean_core\interfaces\hydrodynamics.py", line 709, in connect
    iWP2input = WP2input(Machine,Site)
  File "C:\Users\anambiar\DTOCEAN\lib\site-packages\dtocean_hydro\input.py", line 331, in __init__
    (status, errStr) = self.checkInput()
  File "C:\Users\anambiar\DTOCEAN\lib\site-packages\dtocean_hydro\input.py", line 481, in checkInput
    self.irrotational_flow()
  File "C:\Users\anambiar\DTOCEAN\lib\site-packages\dtocean_hydro\input.py", line 577, in irrotational_flow
    "The execution is terminated")

********************************************************

**Comment by tbloise** [comment]
Hi,

1)	We are trying to use the hydrodynamic module of DTOcean2.0 with real tidal series data. However, we are obtaining an error (as below). This tidal series has a variable velocity along the bathymetry points, as well as a variable velocity over time. Please see below an image that represents a point in time where velocities are variable over the lease area. Please note that – if the same tidal series is used as input on DTOcean1.0 – the hydrodynamic module will run and the tool will not produce any error.

Error (DTOcean2.0):
CRITICAL - dtocean_app.main - An IOError occurred: [Errno The input velocity field is highly rotational ] This violate the model assumption : 'The execution is terminated'

Representative Tidal Series:
![image](https://user-images.githubusercontent.com/36045257/62048166-1301a900-b204-11e9-9269-afea8bc98e7a.png)


2)	We also tried to make a rough assumption of the tidal series (to match the example provided with DTOcean2.0), where the tidal series varies in time, but is constant among the bathymetry points. In this case, we manage to run DTOcean1.0 as well as DTOcean2.0. However, the results are significantly different for the same inputs. 

Could you please advise on that. 
-	Do you have an idea why the rotational error is occurring in DTOcean 2.0 with a realistic tidal series that changes over time and bathymetry points (we already tried to follow you initial suggestion, of changing the ‘probability bins’)? 
-	Why results differ from DTOcean 1.0 and 2.0 for the same inputs, when considering the simplified tidal series, only changing over time?

Many thanks for your time.

Kind regards,

**Comment by H0R5E** [comment]
With regards to your first issue, I am almost certain it's some kind of data corruption / misentry. The check is applied at a fixed time step, so something within one of your time steps is causing the problem, rather than variability over time. I admit, it is hard to track down the problem, as the temporal information is destroyed by the time it reaches the hydrodynamics module. The only way I can help you out and confirm this is if you can share an example file of the problem occurring. 

Assuming there are no data issues with your second example then there may well be differences between versions. I am assuming you mean version 1.0.3 when you say 1.0, in which case there were two significant changes made to the tidal simulations. Firstly, the energy calculations when devices are in yaw was improved. Secondly, the instantaneous power production of the device is capped at its rated power. If you've seen a drop in power then its probably the second change coming into play. If so, check that your power curve and turbine diameter matches your rated power. These changes are all published in the [dtocean-hydrodynamics' change log](https://github.com/DTOcean/dtocean-hydrodynamics/blob/master/CHANGELOG.md), which I invite you to read.
