### ISSUE TITLE
Component Costs Data and its Sources

### ISSUE THREAD

**Issue by lovescienc** [DTOcean/dtocean#35]
Hello,

Thank you very much for the development of the software and the provision of the associated content.
I wonder if there is a list or something similar inside the software (or outside, for example on the project homepage) from which you can see what costs were assumed for which component. Ideally with source reference.

Kind regards,

Vincent

**Comment by H0R5E** [comment]
Hi Vincent,

Regarding the sources of cost data, I'm afraid this information was anonymized or estimated by design as, in general, it's considered commercially sensitive. In most cases this process is also not well documented, but there is the odd [paper](https://www.mdpi.com/1996-1073/10/12/1973) that discusses it. The purpose of the cost data in DTOcean was to give a reasonable estimate at costs, with the expectation that the commercial user would have access to better estimates for the component lists.

The data is stored in the [DTOcean database](https://github.com/DTOcean/dtocean-database). You can search for "cost" on [this page of the documentation](https://dtocean.github.io/user/data_preparation.html) for an overview of what costs are provided. To access the data itself, you will need to install a database manager (see [this video](https://youtu.be/dlthgtsqWAY)) and then restore the database (as in [this video](https://www.youtube.com/watch?v=eIYQPYo8zeQ)). If you install DTOcean, as well, you can dump the database files into excel and csv files (see [here](https://dtocean.github.io/user/gui.html#load-dump)). When you run a simulation, all the relevant cost data is also made accessible in the GUI, which can be modified for the particular simulation being undertaken. So, there are lots of options to access the data!

I hope that helps a bit!

Mat
